### ISSUE TITLE
about the test data

### ISSUE THREAD

**Issue by mmSir** [IceClear/MW-GAN#9]
Hello, when I used the code you gave to test, I found that some videos could not be tested, and the program would report an error. It seems that the network has requirements on the resolution of the input images.For example, the test video "BasketballDrill_832x480_500" will work, but the test video "BasketballDrive_1920x1080_500" will report the following error.May I ask what is the input scale requirement of your network?
![image](https://user-images.githubusercontent.com/35763352/115713017-1bbaeb00-a3a8-11eb-9942-1a1a874f1899.png)
Looking forward to your reply!!

**Comment by IceClear** [comment]
Hi, thanks for your interest. Yes, there is a resolution requirement due to the multi-level WPT operations in the code. Generally, we apply one level WPT for input and 3 level WPT in the pyramid architecture. Thus the size of the image must be the multiple of 2^4. During test, we make sure the size is the multiple of 64 during the data process. you can find the settings here: https://github.com/IceClear/MW-GAN/blob/master/codes/data/data_process.py#L97.

**Comment by mmSir** [comment]
THANKS!
